name: flutter_base
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.1
  cached_network: ^2.1.0
  cached_network_image: ^3.3.1


  html_parser_plus: ^0.1.4


  webview_flutter: ^4.8.0
  flutter_inappwebview: ^6.1.5
  flutter_smart_dialog: ^4.9.7+9
  smart_alert_dialog: ^4.0.4
  adaptive_dialog: ^2.2.1+2
  wolt_modal_sheet: ^0.9.1



  path_provider: ^2.0.14
  share_plus: ^10.1.2
#  app_installer: ^1.3.1  # 安装插件，打开安装界面
  package_info_plus: ^8.1.1
  device_info_plus: ^11.1.1
  url_launcher: ^6.3.0
  permission_handler: ^11.3.1
  internet_connection_checker_plus: ^2.7.0



  logger: ^2.4.0
  talker_flutter: ^4.1.5
#  toastification: ^2.0.0
#  chinese_font_library: ^1.1.0


  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14



  leancloud_storage:
    path: ./plugins/leancloud_storage
  talkingdata_sdk_plugin:
    path: ./plugins/talkingdata_sdk_plugin


  #第三方sdk
  openinstall_flutter_plugin: ^2.5.4
  fl_umeng: ^4.0.2
  fl_umeng_apm: ^1.0.2

  # 模型处理
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1



  json_annotation: ^4.8.1
  copy_with_extension: ^5.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

  json_serializable: ^6.6.1
  copy_with_extension_gen: any

  flutter_gen_runner: ^5.5.0+1


  riverpod_generator: ^2.6.3
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
